cloudformation/senzing-demo-full-stack/cloudformation.yaml
cloudformation/senzing-demo-full-stack/spike-sqs.yaml

Issue 3.dockter.1

---

cloudformation/senzing-demo-full-stack/cloudformation.yaml
docs/senzing-demo-full-stack.md

Issue 3.dockter.2

---

cloudformation/senzing-demo-full-stack/cloudformation.yaml
docs/senzing-demo-full-stack/README.md

Issue 3.dockter.3

---

.project
cloudformation/senzing-demo-full-stack/cloudformation.yaml
cloudformation/senzing-demo-full-stack/spike-bug-assign-public-ip-fix.yaml
cloudformation/senzing-demo-full-stack/spike-bug-assign-public-ip.yaml
docs/senzing-demo-full-stack/README.md

Issue 3.dockter.4

---

cloudformation/senzing-demo-full-stack/spike-cognito-readme.md
cloudformation/senzing-demo-full-stack/spike-cognito.yaml

Issue number: #13
spike on how cognito can be implemented

#13 added spike for cognito and readme

---

cloudformation/senzing-demo-full-stack/cloudformation.yaml
cloudformation/senzing-demo-hosted-zone/cloudformation.yaml
cloudformation/senzing-demo-hosted-zone/spike-https.yaml
cloudformation/staging-test/cloudformation.yaml

Issue 12.dockter.1

---

cloudformation/staging-test/README.md

Issue 16.dockter.1

---

cloudformation/senzing-demo-hosted-zone/cloudformation.yaml
cloudformation/senzing-demo-hosted-zone/spike-https-cognito.yaml
cloudformation/senzing-demo-hosted-zone/spike-https.yaml
cloudformation/senzing-demo-hosted-zone/spike-path-based-routing.yaml

Issue 12.dockter.2

---

README.md

Issue 27.dockter.3

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-senzing-stack-with-choices/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-10M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

Issue 34.dockter.2

---

cloudformation/aws-cloudformation-ecs-staging-simple-100M/README.md
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

Issue 27.dockter.4

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-senzing-stack-with-choices/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-10M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

updated email message

---

cloudformation/aws-cloudformation-ecs-senzing-stack-with-choices/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

#38 added redrive policy to redoer input queue

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#44 added TimeoutAction lambda function

---

docs/aws-cloudformation-ecs-staging-simple/README.md
docs/aws-cloudformation-ecs-user-vpc-hosted-zone/README.md

#46 removed hack for forced scaling from docs

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#49 updated image versions

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#52 updated EFS checking

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#53 lower cased coginito user pool domain

---

cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

57 added a 20M option for data load

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

Issue 56.ron.0

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

60 set load balancer name to support mixed case

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#62 removed private subnet from sshd services

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#65 update memory for key services

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#65 updated cpu for key services

---

cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

Issue 63.ron.0

---

cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

#69 updated stream loader version

---

cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

#71 updated to use 5M

---

cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

#73 updated to use new stream loader

---

cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

Reverts Senzing/aws-cloudformation-ecs#74. this PR should be closed and redone using the new name

Revert "#73 updated to use new stream loader"

---

CHANGELOG.md
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

Issue number: #73 & #77
- Done to all non-spike CFTs:
- Updated security to match what was done for marketplace
- moved images to constants
- added WSS support for the web app
- rearranged parameters to match marketplace

Issue 73.ron.0

---

cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

Issue 79.ron.0

---

CHANGELOG.md
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#92 updates completed

---

cloudformation/aws-cloudformation-ecs-private/README.md
cloudformation/aws-cloudformation-ecs-private/cloudformation-VPC.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-database.yaml

Created new BYO-VPC CFTs

---

cloudformation/aws-cloudformation-ecs-api-gateway/README.md
cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml

Issue number: #94
store API gateway cft

#94 added api gateway cft

---

cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-database.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

Issue number: #96 & #97
???
???

#96 & #97 added autovacuum workers and updated cognito email

---

cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#99 updated yum version

---

CHANGELOG.md
cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#101 removed jupyter

---

CHANGELOG.md
cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#103 removed flow logs

---

CHANGELOG.md
cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-migrate-2.x.x-to-3.0.0/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#119 added suffix to UserPoolDomain

---

.github/workflows/pylint.yaml
.pylintrc

Issue 113.dockter.1

---

CHANGELOG.md
cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-migrate-2.x.x-to-3.0.0/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-database.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#116 updated senzing and image versions

---

CHANGELOG.md
cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-database.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#124 added SecondsBeforeTimeout setting

---

README.md

#125 updated readme

---

cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-migrate-2.x.x-to-3.0.0/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-poc-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-basic.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

Issue number: #131 #130 
???
???

#130 added engine config update #131 updated output

---

cloudformation/aws-cloudformation-ecs-api-gateway/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-certificates/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-full-stack/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-hosted-zone/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-poc-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-private/cloudformation-database.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-user-vpc-hosted-zone/cloudformation.yaml

#137 updated database across all CFTs

---

cloudformation/aws-cloudformation-ecs-poc-simple/CHANGELOG.md
cloudformation/aws-cloudformation-ecs-poc-simple/cloudformation.yaml
cloudformation/aws-cloudformation-ecs-staging-simple-100M/cloudformation.yaml

Issue number: #136 #135 #125
???
???

Issue 136.ron.0

---

README.md

#140 Prepare for deprecation

---

.github/linters/.yaml-lint.yml
.github/workflows/add-labels-standardized.yaml
.github/workflows/add-to-project-garage-dependabot.yaml
.github/workflows/add-to-project-garage.yaml
.github/workflows/dependabot-approve-and-merge.yaml
.github/workflows/lint-workflows.yaml
.github/workflows/pylint.yaml

Issue number: senzing-factory/build-resources#69

senzing-factory/build-resources#69 add linting

---

README.md

#158 archive notes, cleanup links
